import About from '@/components/sections/About'
import Cover from '@/components/sections/Cover'
import Roadmap from '@/components/sections/Roadmap'
import Vision from '@/components/sections/Vision'
import Head from 'next/head'
import brandingImg from "../../public/images/created-by.jpg"
import Image from 'next/image'
import TransitionEffect from '@/components/TransitionEffect'

export default function Home() {
  return (
    <>
      <Head>
        <title>The Odessey Of The UnknownMen</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <TransitionEffect />
      <main className='w-full flex flex-col'>
        <Cover />
        <About />
        <Vision />
        <Roadmap />
        <div className='w-full'>
          <Image src={brandingImg} alt="Unknown Man" className="w-full h-auto" />
        </div>
      </main>
    </>
  )
}
